name: Testsuite
on: [push, pull_request]
jobs:
  test:
    name: Test Code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1.1.4
      - run: poetry install --dev
      - run: pytest
